version: 2
updates:
  # Root package.json
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
      testing:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "playwright"
          - "@playwright/*"

  # Server package
  - package-ecosystem: npm
    directory: "/packages/server"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  # Client package
  - package-ecosystem: npm
    directory: "/packages/client"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  # Shared package
  - package-ecosystem: npm
    directory: "/packages/shared"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  # Plugin Hyperscape
  - package-ecosystem: npm
    directory: "/packages/plugin-hyperscape"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  # 3D Asset Forge
  - package-ecosystem: npm
    directory: "/packages/3d-asset-forge"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3

  # Docker
  - package-ecosystem: docker
    directory: "/packages/server"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3

