
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:29 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 24.3.0 - x86_64
...
