name: Deploy to Railway

on:
  push:
    branches:
      - main
    paths:
      - 'packages/hyperscape/**'
      - 'packages/physx-js-webidl/**'
      - '.github/workflows/deploy-railway.yml'
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: 'bun'

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile

      - name: Type check
        run: |
          cd packages/hyperscape
          bun x tsc --noEmit -p tsconfig.build.json || true
        continue-on-error: true

      - name: Lint
        run: |
          cd packages/hyperscape
          bun run lint || true
        continue-on-error: true

      - name: Build Hyperscape
        run: |
          cd packages/hyperscape
          bun run build

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd packages/hyperscape
          railway up --detach --service hyperscape-server
        
      - name: Verify Deployment
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd packages/hyperscape
          echo "Waiting for deployment to be live..."
          sleep 30
          echo "Deployment triggered successfully!"
          
      - name: Notify on Failure
        if: failure()
        run: |
          echo "::error::Deployment failed. Check logs above for details."

